name: Hourly Data Loop

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is the vital piece!
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install required tools
      run: pip install websockets
    - name: Execute Harvester Script
      run: python harvester.py
    - name: Commit data & update live map
      run: |
        git config --global user.name 'InletDataBot'
        git config --global user.email 'bot@inletdata.internal'
        git add vessel_tracks.csv index.html
        git commit -m "Automated track log update" || exit 0
        git push
